import ThemeProvider from "@/components/ThemeProvider";
import Footer from "@/components/Footer";
import "./globals.css";

export const metadata = {
  title: "Mehran Khaksar",
  description: "Generated by create next app",
  icons: { icon: "./favicon.ico" },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col">
        <ThemeProvider defaultTheme="light" attribute="class">
          <main className="flex-1 pt-5 pb-10 px-2.5 sm:px-0">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
